const char *license =
"<html>\n\n"
"<head>\n\n"
"  <title>GNU General Public License</title>\n\n"
"</head>\n\n"
"<body style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\"\n\n"
" link=\"#1f00ff\" alink=\"#ff0000\" vlink=\"#9900dd\">\n"
"<h1>GNU General Public License</h1>\n"
"<h2>Table of Contents</h2>\n"
"<ul>\n"
"  <li><a name=\"TOC1\" href=\"#SEC1\">GNU GENERAL PUBLIC LICENSE</a>\n"
"    <ul>\n"
"      <li><a name=\"TOC2\" href=\"#SEC2\">Preamble</a> </li>\n"
"      <li><a name=\"TOC3\" href=\"#SEC3\">TERMS AND CONDITIONS FOR\n"
"COPYING, DISTRIBUTION AND MODIFICATION</a> </li>\n"
"    </ul>\n"
"  </li>\n"
"</ul>\n"
"<p> </p>\n"
"<hr>\n"
"<p> </p>\n"
"<h2><a name=\"SEC1\" href=\"#TOC1\">GNU GENERAL PUBLIC LICENSE</a></h2>\n"
"<p> Version 2, June 1991 </p>\n"
"<pre>Copyright (C) 1989, 1991 Free Software Foundation, Inc.  <br>59 Temple Place - Suite 330, Boston, MA  02111-1307, USA<br><br>Everyone is permitted to copy and distribute verbatim copies<br>of this license document, but changing it is not allowed.<br></pre>\n"
"<h2><a name=\"SEC2\" href=\"#TOC2\">Preamble</a></h2>\n"
"<p> The licenses for most software are designed to take away your\n"
"freedom to share and change it.  By contrast, the GNU General Public\n"
"License is intended to guarantee your freedom to share and change free\n"
"software--to make sure the software is free for all its users.  This\n"
"General Public License applies to most of the Free Software Foundation's\n"
"software and to any other program whose authors commit to using it.\n"
"(Some other Free Software Foundation software is covered by the GNU\n"
"Library General Public License instead.)  You can apply it to your\n"
"programs, too. </p>\n"
"<p> When we speak of free software, we are referring to freedom, not\n"
"price. Our General Public Licenses are designed to make sure that you\n"
"have the freedom to distribute copies of free software (and charge for\n"
"this service if you wish), that you receive source code or can get it if\n"
"you want it, that you can change the software or use pieces of it in new\n"
"free programs; and that you know you can do these things. </p>\n"
"<p> To protect your rights, we need to make restrictions that forbid\n"
"anyone to deny you these rights or to ask you to surrender the rights.\n"
"These restrictions translate to certain responsibilities for you if you\n"
"distribute copies of the software, or if you modify it. </p>\n"
"<p> For example, if you distribute copies of such a program, whether\n"
"gratis or for a fee, you must give the recipients all the rights that\n"
"you have.  You must make sure that they, too, receive or can get the\n"
"source code.  And you must show them these terms so they know their\n"
"rights. </p>\n"
"<p> We protect your rights with two steps: (1) copyright the software,\n"
"and (2) offer you this license which gives you legal permission to copy,\n"
"distribute and/or modify the software. </p>\n"
"<p> Also, for each author's protection and ours, we want to make certain\n"
"that everyone understands that there is no warranty for this free\n"
"software. If the software is modified by someone else and passed on, we\n"
"want its recipients to know that what they have is not the original, so\n"
"that any problems introduced by others will not reflect on the original\n"
"authors' reputations. </p>\n"
"<p> Finally, any free program is threatened constantly by software\n"
"patents. We wish to avoid the danger that redistributors of a free\n"
"program will individually obtain patent licenses, in effect making the\n"
"program proprietary.  To prevent this, we have made it clear that any\n"
"patent must be licensed for everyone's free use or not licensed at all. </p>\n"
"<p> The precise terms and conditions for copying, distribution and\n"
"modification follow. </p>\n"
"<h2><a name=\"SEC3\" href=\"#TOC3\">TERMS AND CONDITIONS FOR\n"
"COPYING, DISTRIBUTION AND MODIFICATION</a></h2>\n"
"<p> <strong>0.</strong> This License applies to any program or other\n"
"work which contains a notice placed by the copyright holder saying it\n"
"may be distributed under the terms of this General Public License.  The\n"
"\"Program\", below, refers to any such program or work, and a \"work based\n"
"on the Program\" means either the Program or any derivative work under\n"
"copyright law: that is to say, a work containing the Program or a\n"
"portion of it, either verbatim or with modifications and/or translated\n"
"into another language.  (Hereinafter, translation is included without\n"
"limitation in the term \"modification\".)  Each licensee is addressed as\n"
"\"you\". </p>\n"
"<p> Activities other than copying, distribution and modification are not\n"
"covered by this License; they are outside its scope.  The act of running\n"
"the Program is not restricted, and the output from the Program is\n"
"covered only if its contents constitute a work based on the Program\n"
"(independent of having been made by running the Program). Whether that\n"
"is true depends on what the Program does. </p>\n"
"<p> <strong>1.</strong> You may copy and distribute verbatim copies of\n"
"the Program's source code as you receive it, in any medium, provided\n"
"that you conspicuously and appropriately publish on each copy an\n"
"appropriate copyright notice and disclaimer of warranty; keep intact all\n"
"the notices that refer to this License and to the absence of any\n"
"warranty; and give any other recipients of the Program a copy of this\n"
"License along with the Program. </p>\n"
"<p> You may charge a fee for the physical act of transferring a copy,\n"
"and you may at your option offer warranty protection in exchange for a\n"
"fee. </p>\n"
"<p> <strong>2.</strong> You may modify your copy or copies of the\n"
"Program or any portion of it, thus forming a work based on the Program,\n"
"and copy and distribute such modifications or work under the terms of\n"
"Section 1 above, provided that you also meet all of these conditions: </p>\n"
"<p> </p>\n"
"<ul>\n"
"  <li><strong>a)</strong> You must cause the modified files to carry\n"
"prominent notices      stating that you changed the files and the date\n"
"of any change.\n"
"    <p> </p>\n"
"  </li>\n"
"  <li><strong>b)</strong> You must cause any work that you distribute or\n"
"publish, that in      whole or in part contains or is derived from the\n"
"Program or any      part thereof, to be licensed as a whole at no charge\n"
"to all third      parties under the terms of this License.\n"
"    <p> </p>\n"
"  </li>\n"
"  <li><strong>c)</strong> If the modified program normally reads\n"
"commands interactively      when run, you must cause it, when started\n"
"running for such      interactive use in the most ordinary way, to print\n"
"or display an      announcement including an appropriate copyright\n"
"notice and a      notice that there is no warranty (or else, saying\n"
"that you provide      a warranty) and that users may redistribute the\n"
"program under      these conditions, and telling the user how to view a\n"
"copy of this      License.  (Exception: if the Program itself is\n"
"interactive but      does not normally print such an announcement, your\n"
"work based on      the Program is not required to print an\n"
"announcement.) </li>\n"
"</ul>\n"
"These requirements apply to the modified work as a whole.  If\n"
"identifiable sections of that work are not derived from the Program, and\n"
"can be reasonably considered independent and separate works in\n"
"themselves, then this License, and its terms, do not apply to those\n"
"sections when you distribute them as separate works.  But when you\n"
"distribute the same sections as part of a whole which is a work based on\n"
"the Program, the distribution of the whole must be on the terms of this\n"
"License, whose permissions for other licensees extend to the entire\n"
"whole, and thus to each and every part regardless of who wrote it.\n"
"<p> Thus, it is not the intent of this section to claim rights or\n"
"contest your rights to work written entirely by you; rather, the intent\n"
"is to exercise the right to control the distribution of derivative or\n"
"collective works based on the Program. </p>\n"
"<p> In addition, mere aggregation of another work not based on the\n"
"Program with the Program (or with a work based on the Program) on a\n"
"volume of a storage or distribution medium does not bring the other work\n"
"under the scope of this License. </p>\n"
"<p> <strong>3.</strong> You may copy and distribute the Program (or a\n"
"work based on it, under Section 2) in object code or executable form\n"
"under the terms of Sections 1 and 2 above provided that you also do one\n"
"of the following:<!-- we use this doubled UL to get the sub-sections indented, --><!-- while making the bullets as unobvious as possible. --> </p>\n"
"<ul>\n"
"  <li><strong>a)</strong> Accompany it with the complete corresponding\n"
"machine-readable source code, which must be distributed under the terms\n"
"of Sections      1 and 2 above on a medium customarily used for\n"
"software interchange; or,\n"
"    <p> </p>\n"
"  </li>\n"
"  <li><strong>b)</strong> Accompany it with a written offer, valid for\n"
"at least three      years, to give any third party, for a charge no more\n"
"than your      cost of physically performing source distribution, a\n"
"complete      machine-readable copy of the corresponding source code,\n"
"to be      distributed under the terms of Sections 1 and 2 above on a\n"
"medium customarily used for software interchange; or,\n"
"    <p> </p>\n"
"  </li>\n"
"  <li><strong>c)</strong> Accompany it with the information you received\n"
"as to the offer      to distribute corresponding source code.  (This\n"
"alternative is      allowed only for noncommercial distribution and only\n"
"if you      received the program in object code or executable form with\n"
"such      an offer, in accord with Subsection b above.) </li>\n"
"</ul>\n"
"The source code for a work means the preferred form of the work for\n"
"making modifications to it.  For an executable work, complete source\n"
"code means all the source code for all modules it contains, plus any\n"
"associated interface definition files, plus the scripts used to control\n"
"compilation and installation of the executable.  However, as a special\n"
"exception, the source code distributed need not include anything that is\n"
"normally distributed (in either source or binary form) with the major\n"
"components (compiler, kernel, and so on) of the operating system on\n"
"which the executable runs, unless that component itself accompanies the\n"
"executable.\n"
"<p> If distribution of executable or object code is made by offering\n"
"access to copy from a designated place, then offering equivalent access\n"
"to copy the source code from the same place counts as distribution of\n"
"the source code, even though third parties are not compelled to copy the\n"
"source along with the object code. </p>\n"
"<p> <strong>4.</strong> You may not copy, modify, sublicense, or\n"
"distribute the Program except as expressly provided under this License.\n"
"Any attempt otherwise to copy, modify, sublicense or distribute the\n"
"Program is void, and will automatically terminate your rights under this\n"
"License. However, parties who have received copies, or rights, from you\n"
"under this License will not have their licenses terminated so long as\n"
"such parties remain in full compliance. </p>\n"
"<p> <strong>5.</strong> You are not required to accept this License,\n"
"since you have not signed it.  However, nothing else grants you\n"
"permission to modify or distribute the Program or its derivative works.\n"
"These actions are prohibited by law if you do not accept this License.\n"
"Therefore, by modifying or distributing the Program (or any work based\n"
"on the Program), you indicate your acceptance of this License to do so,\n"
"and all its terms and conditions for copying, distributing or modifying\n"
"the Program or works based on it. </p>\n"
"<p> <strong>6.</strong> Each time you redistribute the Program (or any\n"
"work based on the Program), the recipient automatically receives a\n"
"license from the original licensor to copy, distribute or modify the\n"
"Program subject to these terms and conditions.  You may not impose any\n"
"further restrictions on the recipients' exercise of the rights granted\n"
"herein. You are not responsible for enforcing compliance by third\n"
"parties to this License. </p>\n"
"<p> <strong>7.</strong> If, as a consequence of a court judgment or\n"
"allegation of patent infringement or for any other reason (not limited\n"
"to patent issues), conditions are imposed on you (whether by court\n"
"order, agreement or otherwise) that contradict the conditions of this\n"
"License, they do not excuse you from the conditions of this License. If\n"
"you cannot distribute so as to satisfy simultaneously your obligations\n"
"under this License and any other pertinent obligations, then as a\n"
"consequence you may not distribute the Program at all.  For example, if\n"
"a patent license would not permit royalty-free redistribution of the\n"
"Program by all those who receive copies directly or indirectly through\n"
"you, then the only way you could satisfy both it and this License would\n"
"be to refrain entirely from distribution of the Program. </p>\n"
"<p> If any portion of this section is held invalid or unenforceable\n"
"under any particular circumstance, the balance of the section is\n"

"intended to apply and the section as a whole is intended to apply in\n"
"other circumstances. </p>\n"
"<p> It is not the purpose of this section to induce you to infringe any\n"
"patents or other property right claims or to contest validity of any\n"
"such claims; this section has the sole purpose of protecting the\n"
"integrity of the free software distribution system, which is implemented\n"
"by public license practices.  Many people have made generous\n"
"contributions to the wide range of software distributed through that\n"
"system in reliance on consistent application of that system; it is up to\n"
"the author/donor to decide if he or she is willing to distribute\n"
"software through any other system and a licensee cannot impose that\n"
"choice. </p>\n"
"<p> This section is intended to make thoroughly clear what is believed\n"
"to be a consequence of the rest of this License. </p>\n"
"<p> <strong>8.</strong> If the distribution and/or use of the Program is\n"
"restricted in certain countries either by patents or by copyrighted\n"
"interfaces, the original copyright holder who places the Program under\n"
"this License may add an explicit geographical distribution limitation\n"
"excluding those countries, so that distribution is permitted only in or\n"
"among countries not thus excluded.  In such case, this License\n"
"incorporates the limitation as if written in the body of this License. </p>\n"
"<p> <strong>9.</strong> The Free Software Foundation may publish revised\n"
"and/or new versions of the General Public License from time to time.\n"
"Such new versions will be similar in spirit to the present version, but\n"
"may differ in detail to address new problems or concerns. </p>\n"
"<p> Each version is given a distinguishing version number.  If the\n"
"Program specifies a version number of this License which applies to it\n"
"and \"any later version\", you have the option of following the terms and\n"
"conditions either of that version or of any later version published by\n"
"the Free Software Foundation.  If the Program does not specify a version\n"
"number of this License, you may choose any version ever published by\n"
"the Free Software Foundation. </p>\n"
"<p> <strong>10.</strong> If you wish to incorporate parts of the Program\n"
"into other free programs whose distribution conditions are different,\n"
"write to the author to ask for permission.  For software which is\n"
"copyrighted by the Free Software Foundation, write to the Free Software\n"
"Foundation; we sometimes make exceptions for this.  Our decision will be\n"
"guided by the two goals of preserving the free status of all\n"
"derivatives of our free software and of promoting the sharing and reuse\n"
"of software generally. </p>\n"
"<p><strong>NO WARRANTY</strong></p>\n"
"<p> <strong>11.</strong> BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE,\n"
"THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY\n"
"APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT\n"
"HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\" WITHOUT\n"
"WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n"
"PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE\n"
"OF THE PROGRAM IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU\n"
"ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. </p>\n"
"<p> <strong>12.</strong> IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW\n"

"OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY\n"
"WHO MAY MODIFY AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE\n"
"LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR\n"
"CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE\n"
"PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING\n"
"RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A\n"
"FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH\n"
"HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\n"
"DAMAGES. </p>\n"
"<h2>END OF TERMS AND CONDITIONS</h2>\n"
"<hr>\n"
"</body>\n"
"</html>";
