// ---------------------------------------------------------------------------
// _luaif/dpm_netx5_lua.cpp was generated by genwxbind.lua 
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#include "wx/wxprec.h"

#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif


#include "wxlua/include/wxlstate.h"
#include "dpm_netx5_wxlua_bindings.h"


// ---------------------------------------------------------------------------
// Bind class dpm
// ---------------------------------------------------------------------------

// Lua MetaTable Tag for Class 'dpm'
int wxluatype_dpm = WXLUA_TUNKNOWN;

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_connect[] = { &wxluatype_dpm, NULL };
static int LUACALL wxLua_dpm_connect(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_connect[1] = {{ wxLua_dpm_connect, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_dpm_connect }};
//  void connect()
static int LUACALL wxLua_dpm_connect(lua_State *L)
{
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call connect
    self->connect();

    return 0;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_delete[] = { &wxluatype_dpm, NULL };
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_delete[1] = {{ wxlua_userdata_delete, WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, 1, 1, s_wxluatypeArray_wxLua_dpm_delete }};

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_disconnect[] = { &wxluatype_dpm, NULL };
static int LUACALL wxLua_dpm_disconnect(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_disconnect[1] = {{ wxLua_dpm_disconnect, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_dpm_disconnect }};
//  void disconnect()
static int LUACALL wxLua_dpm_disconnect(lua_State *L)
{
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call disconnect
    self->disconnect();

    return 0;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_get_name[] = { &wxluatype_dpm, NULL };
static int LUACALL wxLua_dpm_get_name(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_get_name[1] = {{ wxLua_dpm_get_name, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_dpm_get_name }};
//  wxString get_name()
static int LUACALL wxLua_dpm_get_name(lua_State *L)
{
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call get_name
    wxString returns = (self->get_name());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_get_typ[] = { &wxluatype_dpm, NULL };
static int LUACALL wxLua_dpm_get_typ(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_get_typ[1] = {{ wxLua_dpm_get_typ, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_dpm_get_typ }};
//  wxString get_typ()
static int LUACALL wxLua_dpm_get_typ(lua_State *L)
{
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call get_typ
    wxString returns = (self->get_typ());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_is_connected[] = { &wxluatype_dpm, NULL };
static int LUACALL wxLua_dpm_is_connected(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_is_connected[1] = {{ wxLua_dpm_is_connected, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_dpm_is_connected }};
//  bool is_connected()
static int LUACALL wxLua_dpm_is_connected(lua_State *L)
{
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call is_connected
    bool returns = (self->is_connected());
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_read_data08[] = { &wxluatype_dpm, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_dpm_read_data08(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_read_data08[1] = {{ wxLua_dpm_read_data08, WXLUAMETHOD_METHOD, 2, 2, s_wxluatypeArray_wxLua_dpm_read_data08 }};
//  unsigned char read_data08(unsigned long ulNetxAddress)
static int LUACALL wxLua_dpm_read_data08(lua_State *L)
{
    // unsigned long ulNetxAddress
    unsigned long ulNetxAddress = (long)wxlua_getnumbertype(L, 2);
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call read_data08
    unsigned char returns = (self->read_data08(ulNetxAddress));
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_read_data16[] = { &wxluatype_dpm, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_dpm_read_data16(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_read_data16[1] = {{ wxLua_dpm_read_data16, WXLUAMETHOD_METHOD, 2, 2, s_wxluatypeArray_wxLua_dpm_read_data16 }};
//  unsigned short read_data16(unsigned long ulNetxAddress)
static int LUACALL wxLua_dpm_read_data16(lua_State *L)
{
    // unsigned long ulNetxAddress
    unsigned long ulNetxAddress = (long)wxlua_getnumbertype(L, 2);
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call read_data16
    unsigned short returns = (self->read_data16(ulNetxAddress));
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_read_data32[] = { &wxluatype_dpm, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_dpm_read_data32(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_read_data32[1] = {{ wxLua_dpm_read_data32, WXLUAMETHOD_METHOD, 2, 2, s_wxluatypeArray_wxLua_dpm_read_data32 }};
//  unsigned long read_data32(unsigned long ulNetxAddress)
static int LUACALL wxLua_dpm_read_data32(lua_State *L)
{
    // unsigned long ulNetxAddress
    unsigned long ulNetxAddress = (long)wxlua_getnumbertype(L, 2);
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call read_data32
    unsigned long returns = (self->read_data32(ulNetxAddress));
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_read_image[] = { &wxluatype_dpm, &wxluatype_TNUMBER, &wxluatype_TNUMBER, &wxluatype_TFUNCTION, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_dpm_read_image(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_read_image[1] = {{ wxLua_dpm_read_image, WXLUAMETHOD_METHOD, 5, 5, s_wxluatypeArray_wxLua_dpm_read_image }};
// %override wxLua_dpm_read_image
static int LUACALL wxLua_dpm_read_image(lua_State *L)
{
    int iLuaCallbackTag;
    wxLuaState wxlState(L);
    wxString returns;
    // voidptr_long vplCallbackUserData
    long vplCallbackUserData = (long)wxlua_getnumbertype(L, 5);
    // LuaFunction fnCallback
    if( lua_isfunction(L, 4) )
    {
        // push function to top of stack
        lua_pushvalue(L, 4);
        // ref function and pop it from stack
        iLuaCallbackTag = luaL_ref(L, LUA_REGISTRYINDEX);
    }
    else
    {
        // no callback function provided
        wxlua_argerror(L, 4, wxT("a 'function'"));
    }
    // unsigned long ulSize
    unsigned long ulSize = (long)wxlua_getnumbertype(L, 3);
    // unsigned long ulNetxAddress
    unsigned long ulNetxAddress = (long)wxlua_getnumbertype(L, 2);
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call read_image
    returns = (self->read_image(ulNetxAddress, ulSize, L, iLuaCallbackTag, (void*)vplCallbackUserData));

    // remove ref to function
    luaL_unref(L, LUA_REGISTRYINDEX, iLuaCallbackTag);

    // push the result string
    wxlState.lua_PushLString(returns,returns.Len());

    return 1;
}


static wxLuaArgType s_wxluatypeArray_wxLua_dpm_write_data08[] = { &wxluatype_dpm, &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_dpm_write_data08(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_write_data08[1] = {{ wxLua_dpm_write_data08, WXLUAMETHOD_METHOD, 3, 3, s_wxluatypeArray_wxLua_dpm_write_data08 }};
//  void write_data08(unsigned long ulNetxAddress, unsigned char bData)
static int LUACALL wxLua_dpm_write_data08(lua_State *L)
{
    // unsigned char bData
    unsigned char bData = (char)wxlua_getnumbertype(L, 3);
    // unsigned long ulNetxAddress
    unsigned long ulNetxAddress = (long)wxlua_getnumbertype(L, 2);
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call write_data08
    self->write_data08(ulNetxAddress, bData);

    return 0;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_write_data16[] = { &wxluatype_dpm, &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_dpm_write_data16(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_write_data16[1] = {{ wxLua_dpm_write_data16, WXLUAMETHOD_METHOD, 3, 3, s_wxluatypeArray_wxLua_dpm_write_data16 }};
//  void write_data16(unsigned long ulNetxAddress, unsigned short usData)
static int LUACALL wxLua_dpm_write_data16(lua_State *L)
{
    // unsigned short usData
    unsigned short usData = (short)wxlua_getnumbertype(L, 3);
    // unsigned long ulNetxAddress
    unsigned long ulNetxAddress = (long)wxlua_getnumbertype(L, 2);
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call write_data16
    self->write_data16(ulNetxAddress, usData);

    return 0;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_write_data32[] = { &wxluatype_dpm, &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_dpm_write_data32(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_write_data32[1] = {{ wxLua_dpm_write_data32, WXLUAMETHOD_METHOD, 3, 3, s_wxluatypeArray_wxLua_dpm_write_data32 }};
//  void write_data32(unsigned long ulNetxAddress, unsigned long ulData)
static int LUACALL wxLua_dpm_write_data32(lua_State *L)
{
    // unsigned long ulData
    unsigned long ulData = (long)wxlua_getnumbertype(L, 3);
    // unsigned long ulNetxAddress
    unsigned long ulNetxAddress = (long)wxlua_getnumbertype(L, 2);
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call write_data32
    self->write_data32(ulNetxAddress, ulData);

    return 0;
}

static wxLuaArgType s_wxluatypeArray_wxLua_dpm_write_image[] = { &wxluatype_dpm, &wxluatype_TNUMBER, &wxluatype_TSTRING, &wxluatype_TFUNCTION, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_dpm_write_image(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_dpm_write_image[1] = {{ wxLua_dpm_write_image, WXLUAMETHOD_METHOD, 5, 5, s_wxluatypeArray_wxLua_dpm_write_image }};
// %override wxLua_dpm_write_image
static int LUACALL wxLua_dpm_write_image(lua_State *L)
{
    int iLuaCallbackTag;
    wxLuaState wxlState(L);
    // voidptr_long vplCallbackUserData
    long vplCallbackUserData = (long)wxlua_getnumbertype(L, 5);
    // LuaFunction fnCallback
    if( lua_isfunction(L, 4) )
    {
        // push function to top of stack
        lua_pushvalue(L, 4);
        // ref function and pop it from stack
        iLuaCallbackTag = luaL_ref(L, LUA_REGISTRYINDEX);
    }
    else
    {
        // no callback function provided
        wxlua_argerror(L, 4, wxT("a 'function'"));
    }
    // wxString strData
    wxString strData;
    size_t sizLen;
    const char *pcBuf;
    pcBuf = lua_tolstring(L, 3, &sizLen);
    if( sizLen==0 )
    {
        strData = wxEmptyString;
    }
    else
    {
        strData = wxString::From8BitData(pcBuf, sizLen);
    }
    // unsigned long ulNetxAddress
    unsigned long ulNetxAddress = (long)wxlua_getnumbertype(L, 2);
    // get this
    dpm * self = (dpm *)wxluaT_getuserdatatype(L, 1, wxluatype_dpm);
    // call write_image
    self->write_image(ulNetxAddress, strData, L, iLuaCallbackTag, (void*)vplCallbackUserData);

    // remove ref to function
    luaL_unref(L, LUA_REGISTRYINDEX, iLuaCallbackTag);

    return 0;
}




// Map Lua Class Methods to C Binding Functions
wxLuaBindMethod dpm_methods[] = {
    { "connect", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_connect, 1, NULL },
    { "delete", WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, s_wxluafunc_wxLua_dpm_delete, 1, NULL },
    { "disconnect", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_disconnect, 1, NULL },
    { "get_name", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_get_name, 1, NULL },
    { "get_typ", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_get_typ, 1, NULL },
    { "is_connected", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_is_connected, 1, NULL },
    { "read_data08", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_read_data08, 1, NULL },
    { "read_data16", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_read_data16, 1, NULL },
    { "read_data32", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_read_data32, 1, NULL },
    { "read_image", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_read_image, 1, NULL },
    { "write_data08", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_write_data08, 1, NULL },
    { "write_data16", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_write_data16, 1, NULL },
    { "write_data32", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_write_data32, 1, NULL },
    { "write_image", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_dpm_write_image, 1, NULL },
    { 0, 0, 0, 0 },
};

int dpm_methodCount = sizeof(dpm_methods)/sizeof(wxLuaBindMethod) - 1;


