/*---------------------------------------------------------------------------
 * Please note:
 *   This file is generated by scons. All changes will be lost!
 --------------------------------------------------------------------------*/


#ifndef __CRYPTO_VERSION_H__
#define __CRYPTO_VERSION_H__

#define CRYPTO_VERSION_MAJ ${PROJECT_VERSION_MAJ}
#define CRYPTO_VERSION_MIN ${PROJECT_VERSION_MIN}
#define CRYPTO_VERSION_SVN "${PROJECT_VERSION_SVN}"
#define CRYPTO_VERSION_ALL "${PROJECT_VERSION_MAJ}.${PROJECT_VERSION_MIN}.${PROJECT_VERSION_SVN}"


#endif	/* __CRYPTO_VERSION_H__ */

