// ---------------------------------------------------------------------------
// _luaif/mhash_lua.cpp was generated by genwxbind.lua 
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#include "wx/wxprec.h"

#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif


#include "wxlua/include/wxlstate.h"
#include "mhash_wxlua_bindings.h"
#include "application/mhash_lua_interface.h"

// ---------------------------------------------------------------------------
// Bind class mhash_state
// ---------------------------------------------------------------------------

// Lua MetaTable Tag for Class 'mhash_state'
int wxluatype_mhash_state = WXLUA_TUNKNOWN;

static int LUACALL wxLua_mhash_state_count(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_count[1] = {{ wxLua_mhash_state_count, WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, 0, 0, g_wxluaargtypeArray_None }};
// 	static double count()
static int LUACALL wxLua_mhash_state_count(lua_State *L)
{
    // call count
    double returns = (mhash_state::count());
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_delete[] = { &wxluatype_mhash_state, NULL };
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_delete[1] = {{ wxlua_userdata_delete, WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, 1, 1, s_wxluatypeArray_wxLua_mhash_state_delete }};

static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_get_block_size[] = { &wxluatype_TINTEGER, NULL };
static int LUACALL wxLua_mhash_state_get_block_size(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_get_block_size[1] = {{ wxLua_mhash_state_get_block_size, WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, 1, 1, s_wxluatypeArray_wxLua_mhash_state_get_block_size }};
// 	static double get_block_size(hashid type)
static int LUACALL wxLua_mhash_state_get_block_size(lua_State *L)
{
    // hashid type
    hashid type = (hashid)wxlua_getintegertype(L, 1);
    // call get_block_size
    double returns = (mhash_state::get_block_size(type));
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_get_hash_name[] = { &wxluatype_TINTEGER, NULL };
static int LUACALL wxLua_mhash_state_get_hash_name(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_get_hash_name[1] = {{ wxLua_mhash_state_get_hash_name, WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, 1, 1, s_wxluatypeArray_wxLua_mhash_state_get_hash_name }};
// 	static wxString get_hash_name(hashid type)
static int LUACALL wxLua_mhash_state_get_hash_name(lua_State *L)
{
    // hashid type
    hashid type = (hashid)wxlua_getintegertype(L, 1);
    // call get_hash_name
    wxString returns = (mhash_state::get_hash_name(type));
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static int LUACALL wxLua_mhash_state_get_version(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_get_version[1] = {{ wxLua_mhash_state_get_version, WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, 0, 0, g_wxluaargtypeArray_None }};
// 	static wxString get_version()
static int LUACALL wxLua_mhash_state_get_version(lua_State *L)
{
    // call get_version
    wxString returns = (mhash_state::get_version());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_hash[] = { &wxluatype_mhash_state, &wxluatype_TSTRING, NULL };
static int LUACALL wxLua_mhash_state_hash(lua_State *L);
// static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_hash[1] = {{ wxLua_mhash_state_hash, WXLUAMETHOD_METHOD, 2, 2, s_wxluatypeArray_wxLua_mhash_state_hash }};
// %override wxLua_mhash_state_hash
static int LUACALL wxLua_mhash_state_hash(lua_State *L)
{
	size_t sizLen;
	const char *pcBuf;
	double dData_Size;
	mhash_state *ptSelf;


	// get the 'strData' parameter and it's size
	pcBuf = lua_tolstring(L, 2, &sizLen);
	dData_Size = (double)sizLen;

	// get this
	ptSelf = (mhash_state *)wxluaT_getuserdatatype(L, 1, wxluatype_mhash_state);

	// call hash
	ptSelf->hash(L, pcBuf, dData_Size, 0);

	return 0;
}


static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_hash1[] = { &wxluatype_mhash_state, &wxluatype_TSTRING, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_mhash_state_hash1(lua_State *L);
// static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_hash1[1] = {{ wxLua_mhash_state_hash1, WXLUAMETHOD_METHOD, 3, 3, s_wxluatypeArray_wxLua_mhash_state_hash1 }};
// %override wxLua_mhash_state_hash1
static int LUACALL wxLua_mhash_state_hash1(lua_State *L)
{
	size_t sizLen;
	double dData_Size;
	const char *pcBuf;
	double dParam_Size;
	mhash_state *ptSelf;


	// get the 'strData' parameter and it's size
	pcBuf = lua_tolstring(L, 2, &sizLen);
	dData_Size = (double)sizLen;

	// get the 'size' parameter
	dParam_Size = (double)wxlua_getnumbertype(L, 3);

	// check if the requested size exceeds the string
	if( dParam_Size>dData_Size )
	{
		dParam_Size = dData_Size;
	}

	// get this
	ptSelf = (mhash_state *)wxluaT_getuserdatatype(L, 1, wxluatype_mhash_state);

	// call hash
	ptSelf->hash(L, pcBuf, dParam_Size, 0);

	return 0;
}


static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_hash2[] = { &wxluatype_mhash_state, &wxluatype_TSTRING, &wxluatype_TNUMBER, &wxluatype_TNUMBER, NULL };
static int LUACALL wxLua_mhash_state_hash2(lua_State *L);
// static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_hash2[1] = {{ wxLua_mhash_state_hash2, WXLUAMETHOD_METHOD, 4, 4, s_wxluatypeArray_wxLua_mhash_state_hash2 }};
// %override wxLua_mhash_state_hash2
static int LUACALL wxLua_mhash_state_hash2(lua_State *L)
{
	size_t sizLen;
	double dData_Size;
	const char *pcBuf;
	double dParam_Size;
	double dParam_Offset;
	mhash_state *ptSelf;


	// get the 'strData' parameter and it's size
	pcBuf = lua_tolstring(L, 2, &sizLen);
	dData_Size = (double)sizLen;

	// get the 'size' parameter
	dParam_Size = (double)wxlua_getnumbertype(L, 3);

	// get the 'offset' parameter
	dParam_Offset = (double)wxlua_getnumbertype(L, 4);

	// check if the requested offset exceeds the data
	if( dParam_Offset<dData_Size )
	{
		// offset is within data

		// check if the requested size exceeds the string
		if( dParam_Offset+dParam_Size>dData_Size )
		{
			dParam_Size = dData_Size - dParam_Offset;
		}

		// get this
		ptSelf = (mhash_state *)wxluaT_getuserdatatype(L, 1, wxluatype_mhash_state);

		// call hash
		ptSelf->hash(L, pcBuf, dParam_Size, dParam_Offset);
	}

	return 0;
}


static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_hash_end[] = { &wxluatype_mhash_state, NULL };
static int LUACALL wxLua_mhash_state_hash_end(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_hash_end[1] = {{ wxLua_mhash_state_hash_end, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_mhash_state_hash_end }};
// %override wxLua_mhash_state_hash_end
static int LUACALL wxLua_mhash_state_hash_end(lua_State *L)
{
	wxLuaState wxlState(L);
	mhash_state *ptSelf;
	wxString strHash;

	// get this
	ptSelf = (mhash_state *)wxluaT_getuserdatatype(L, 1, wxluatype_mhash_state);

	// call hash_end
	strHash = ptSelf->hash_end();

	// push the result string
	wxlState.lua_PushLString(strHash, strHash.Len());

	return 1;
}


static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_init[] = { &wxluatype_mhash_state, &wxluatype_TINTEGER, NULL };
static int LUACALL wxLua_mhash_state_init(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_init[1] = {{ wxLua_mhash_state_init, WXLUAMETHOD_METHOD, 2, 2, s_wxluatypeArray_wxLua_mhash_state_init }};
// 	void init(hashid type)
static int LUACALL wxLua_mhash_state_init(lua_State *L)
{
    // hashid type
    hashid type = (hashid)wxlua_getintegertype(L, 2);
    // get this
    mhash_state * self = (mhash_state *)wxluaT_getuserdatatype(L, 1, wxluatype_mhash_state);
    // call init
    self->init(type);

    return 0;
}

static int LUACALL wxLua_mhash_state_constructor(lua_State *L);
// static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_constructor[1] = {{ wxLua_mhash_state_constructor, WXLUAMETHOD_CONSTRUCTOR, 0, 0, g_wxluaargtypeArray_None }};
// 	mhash_state()
static int LUACALL wxLua_mhash_state_constructor(lua_State *L)
{
    // call constructor
    mhash_state* returns = new mhash_state();
    // add to tracked memory list
    wxluaO_addgcobject(L, returns);
    // push the constructed class pointer
    wxluaT_pushuserdatatype(L, returns, wxluatype_mhash_state);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_constructor1[] = { &wxluatype_TINTEGER, NULL };
static int LUACALL wxLua_mhash_state_constructor1(lua_State *L);
// static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_constructor1[1] = {{ wxLua_mhash_state_constructor1, WXLUAMETHOD_CONSTRUCTOR, 1, 1, s_wxluatypeArray_wxLua_mhash_state_constructor1 }};
// 	mhash_state(hashid type)
static int LUACALL wxLua_mhash_state_constructor1(lua_State *L)
{
    // hashid type
    hashid type = (hashid)wxlua_getintegertype(L, 1);
    // call constructor
    mhash_state* returns = new mhash_state(type);
    // add to tracked memory list
    wxluaO_addgcobject(L, returns);
    // push the constructed class pointer
    wxluaT_pushuserdatatype(L, returns, wxluatype_mhash_state);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_mhash_state_constructor2[] = { &wxluatype_mhash_state, NULL };
static int LUACALL wxLua_mhash_state_constructor2(lua_State *L);
// static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_constructor2[1] = {{ wxLua_mhash_state_constructor2, WXLUAMETHOD_CONSTRUCTOR, 1, 1, s_wxluatypeArray_wxLua_mhash_state_constructor2 }};
// 	mhash_state(mhash_state *ptMHash)
static int LUACALL wxLua_mhash_state_constructor2(lua_State *L)
{
    // mhash_state ptMHash
    mhash_state * ptMHash = (mhash_state *)wxluaT_getuserdatatype(L, 1, wxluatype_mhash_state);
    // call constructor
    mhash_state* returns = new mhash_state(ptMHash);
    // add to tracked memory list
    wxluaO_addgcobject(L, returns);
    // push the constructed class pointer
    wxluaT_pushuserdatatype(L, returns, wxluatype_mhash_state);

    return 1;
}



// function overload table
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_hash_overload[] =
{
    { wxLua_mhash_state_hash, WXLUAMETHOD_METHOD, 2, 2, s_wxluatypeArray_wxLua_mhash_state_hash },
    { wxLua_mhash_state_hash1, WXLUAMETHOD_METHOD, 3, 3, s_wxluatypeArray_wxLua_mhash_state_hash1 },
    { wxLua_mhash_state_hash2, WXLUAMETHOD_METHOD, 4, 4, s_wxluatypeArray_wxLua_mhash_state_hash2 },
};
static int s_wxluafunc_wxLua_mhash_state_hash_overload_count = sizeof(s_wxluafunc_wxLua_mhash_state_hash_overload)/sizeof(wxLuaBindCFunc);

// function overload table
static wxLuaBindCFunc s_wxluafunc_wxLua_mhash_state_constructor_overload[] =
{
    { wxLua_mhash_state_constructor, WXLUAMETHOD_CONSTRUCTOR, 0, 0, g_wxluaargtypeArray_None },
    { wxLua_mhash_state_constructor1, WXLUAMETHOD_CONSTRUCTOR, 1, 1, s_wxluatypeArray_wxLua_mhash_state_constructor1 },
    { wxLua_mhash_state_constructor2, WXLUAMETHOD_CONSTRUCTOR, 1, 1, s_wxluatypeArray_wxLua_mhash_state_constructor2 },
};
static int s_wxluafunc_wxLua_mhash_state_constructor_overload_count = sizeof(s_wxluafunc_wxLua_mhash_state_constructor_overload)/sizeof(wxLuaBindCFunc);


// Map Lua Class Methods to C Binding Functions
wxLuaBindMethod mhash_state_methods[] = {
    { "count", WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, s_wxluafunc_wxLua_mhash_state_count, 1, NULL },
    { "delete", WXLUAMETHOD_METHOD|WXLUAMETHOD_DELETE, s_wxluafunc_wxLua_mhash_state_delete, 1, NULL },
    { "get_block_size", WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, s_wxluafunc_wxLua_mhash_state_get_block_size, 1, NULL },
    { "get_hash_name", WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, s_wxluafunc_wxLua_mhash_state_get_hash_name, 1, NULL },
    { "get_version", WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, s_wxluafunc_wxLua_mhash_state_get_version, 1, NULL },

    { "hash", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_mhash_state_hash_overload, s_wxluafunc_wxLua_mhash_state_hash_overload_count, 0 },

    { "hash_end", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_mhash_state_hash_end, 1, NULL },
    { "init", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_mhash_state_init, 1, NULL },

    { "mhash_state", WXLUAMETHOD_CONSTRUCTOR, s_wxluafunc_wxLua_mhash_state_constructor_overload, s_wxluafunc_wxLua_mhash_state_constructor_overload_count, 0 },

    { 0, 0, 0, 0 },
};

int mhash_state_methodCount = sizeof(mhash_state_methods)/sizeof(wxLuaBindMethod) - 1;


