// ---------------------------------------------------------------------------
// This file was generated by genwxbind.lua 
//
// Any changes made to this file may be lost when file is regenerated.
// ---------------------------------------------------------------------------

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#include "wx/wxprec.h"


#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif

#include "wxlua/include/wxlstate.h"
#include "muhkuh_wxlua_bindings.h"


// ---------------------------------------------------------------------------
// wxLuaGetEventList_muhkuh_lua() is called to register events
// ---------------------------------------------------------------------------

wxLuaBindEvent* wxLuaGetEventList_muhkuh_lua(size_t &count)
{
    static wxLuaBindEvent eventList[] =
    {

        { 0, 0, 0 },
    };
    count = sizeof(eventList)/sizeof(wxLuaBindEvent) - 1;
    return eventList;
}

// ---------------------------------------------------------------------------
// wxLuaGetDefineList_muhkuh_lua() is called to register %define and %enum
// ---------------------------------------------------------------------------

wxLuaBindDefine* wxLuaGetDefineList_muhkuh_lua(size_t &count)
{
    static wxLuaBindDefine defineList[] =
    {

        { 0, 0 },
    };
    count = sizeof(defineList)/sizeof(wxLuaBindDefine) - 1;
    return defineList;
}

// ---------------------------------------------------------------------------

// wxLuaGetStringList_muhkuh_lua() is called to register %define %string
// ---------------------------------------------------------------------------

wxLuaBindString* wxLuaGetStringList_muhkuh_lua(size_t &count)
{
    static wxLuaBindString stringList[] =
    {

        { 0, 0 },
    };
    count = sizeof(stringList)/sizeof(wxLuaBindString) - 1;
    return stringList;
}

// ---------------------------------------------------------------------------
// wxLuaGetObjectList_muhkuh_lua() is called to register object and pointer bindings
// ---------------------------------------------------------------------------

wxLuaBindObject* wxLuaGetObjectList_muhkuh_lua(size_t &count)
{
    static wxLuaBindObject objectList[] =
    {

        { 0, 0, 0, 0 },
    };
    count = sizeof(objectList)/sizeof(wxLuaBindObject) - 1;
    return objectList;
}

// ---------------------------------------------------------------------------
// wxLuaGetFunctionList_muhkuh_lua() is called to register global functions
// ---------------------------------------------------------------------------

// %function %gc muhkuh_plugin_instance *GetNextPlugin()
static int LUACALL wxLua_function_GetNextPlugin(lua_State *L)
{
    wxLuaState wxlState(L);
    muhkuh_plugin_instance *returns;
    // call GetNextPlugin
    returns = (muhkuh_plugin_instance *)GetNextPlugin();
    if (!wxlState.IsTrackedObject(returns)) wxlState.AddTrackedObject(returns);
    // push the result datatype
    wxlState.PushUserDataType(s_wxluatag_muhkuh_plugin_instance, returns);

    return 1;
}
static wxLuaBindCFunc s_wxluafunc_wxLua_function_GetNextPlugin[1] = {{ wxLua_function_GetNextPlugin, WXLUAMETHOD_CFUNCTION, 0, 0, s_wxluaargArray_None }};

static wxLuaArgTag s_wxluatagArray_wxLua_function_ScanPlugins[] = { &s_wxluaarg_String, NULL };
// %function void ScanPlugins(wxString strPattern)
static int LUACALL wxLua_function_ScanPlugins(lua_State *L)
{
    wxLuaState wxlState(L);
    // wxString strPattern
    wxString strPattern = wxlState.GetwxStringType(1);
    // call ScanPlugins
    ScanPlugins(strPattern);

    return 0;
}
static wxLuaBindCFunc s_wxluafunc_wxLua_function_ScanPlugins[1] = {{ wxLua_function_ScanPlugins, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatagArray_wxLua_function_ScanPlugins }};

// %function void TestHasFinished()
static int LUACALL wxLua_function_TestHasFinished(lua_State *L)
{
    // call TestHasFinished
    TestHasFinished();

    return 0;
}
static wxLuaBindCFunc s_wxluafunc_wxLua_function_TestHasFinished[1] = {{ wxLua_function_TestHasFinished, WXLUAMETHOD_CFUNCTION, 0, 0, s_wxluaargArray_None }};

static wxLuaArgTag s_wxluatagArray_wxLua_function_include[] = { &s_wxluaarg_String, &s_wxluaarg_String, NULL };
// %function void include(wxString strFileName, wxString strChunkName)
static int LUACALL wxLua_function_include(lua_State *L)
{
    wxLuaState wxlState(L);
    // wxString strChunkName
    wxString strChunkName = wxlState.GetwxStringType(2);
    // wxString strFileName
    wxString strFileName = wxlState.GetwxStringType(1);
    // call include
    include(strFileName, strChunkName);

    return 0;
}
static wxLuaBindCFunc s_wxluafunc_wxLua_function_include[1] = {{ wxLua_function_include, WXLUAMETHOD_CFUNCTION, 2, 2, s_wxluatagArray_wxLua_function_include }};

static wxLuaArgTag s_wxluatagArray_wxLua_function_load[] = { &s_wxluaarg_String, NULL };
// %function wxString load(wxString strFileName)
static int LUACALL wxLua_function_load(lua_State *L)
{
    wxLuaState wxlState(L);
    wxString returns;
    // wxString strFileName
    wxString strFileName = wxlState.GetwxStringType(1);
    // call load
    returns = (load(strFileName));
    // push the result string
    wxlState.lua_PushLString(returns,returns.Len());

    return 1;
}
static wxLuaBindCFunc s_wxluafunc_wxLua_function_load[1] = {{ wxLua_function_load, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatagArray_wxLua_function_load }};

// ---------------------------------------------------------------------------
// wxLuaGetFunctionList_muhkuh_lua() is called to register global functions
// ---------------------------------------------------------------------------

wxLuaBindMethod* wxLuaGetFunctionList_muhkuh_lua(size_t &count)
{
    static wxLuaBindMethod functionList[] =
    {
        { "GetNextPlugin", WXLUAMETHOD_CFUNCTION, s_wxluafunc_wxLua_function_GetNextPlugin, 1, NULL },
        { "ScanPlugins", WXLUAMETHOD_CFUNCTION, s_wxluafunc_wxLua_function_ScanPlugins, 1, NULL },
        { "TestHasFinished", WXLUAMETHOD_CFUNCTION, s_wxluafunc_wxLua_function_TestHasFinished, 1, NULL },
        { "include", WXLUAMETHOD_CFUNCTION, s_wxluafunc_wxLua_function_include, 1, NULL },
        { "load", WXLUAMETHOD_CFUNCTION, s_wxluafunc_wxLua_function_load, 1, NULL },

        { 0, 0, 0, 0 }, 
    };
    count = sizeof(functionList)/sizeof(wxLuaBindMethod) - 1;
    return functionList;
}



// ---------------------------------------------------------------------------
// wxLuaGetClassList_muhkuh_lua() is called to register classes
// ---------------------------------------------------------------------------

wxLuaBindClass* wxLuaGetClassList_muhkuh_lua(size_t &count)
{
    static wxLuaBindClass classList[] =
    {
        { "muhkuh_plugin_instance", muhkuh_plugin_instance_methods, muhkuh_plugin_instance_methodCount, NULL, &s_wxluatag_muhkuh_plugin_instance, NULL, NULL ,s_wxluadefineArray_None, 0, }, 

        { 0, 0, 0, 0, 0, 0, 0 }, 
    };
    count = sizeof(classList)/sizeof(wxLuaBindClass) - 1;

    return classList;
}


// ---------------------------------------------------------------------------
// wxLuaBinding_muhkuh_lua() - the binding class
// ---------------------------------------------------------------------------

// binding class
extern wxLuaBindClass  *wxLuaGetClassList_muhkuh_lua(size_t &count);
extern wxLuaBindDefine *wxLuaGetDefineList_muhkuh_lua(size_t &count);
extern wxLuaBindString *wxLuaGetStringList_muhkuh_lua(size_t &count);
extern wxLuaBindEvent  *wxLuaGetEventList_muhkuh_lua(size_t &count);
extern wxLuaBindObject *wxLuaGetObjectList_muhkuh_lua(size_t &count);
extern wxLuaBindMethod *wxLuaGetFunctionList_muhkuh_lua(size_t &count);


IMPLEMENT_DYNAMIC_CLASS(wxLuaBinding_muhkuh_lua, wxLuaBinding)

wxLuaBinding_muhkuh_lua::wxLuaBinding_muhkuh_lua() : wxLuaBinding()
{
    m_bindingName   = wxT("muhkuh_lua");
    m_nameSpace     = wxT("muhkuh");
    m_classArray    = wxLuaGetClassList_muhkuh_lua(m_classCount);
    m_defineArray   = wxLuaGetDefineList_muhkuh_lua(m_defineCount);
    m_stringArray   = wxLuaGetStringList_muhkuh_lua(m_stringCount);
    m_eventArray    = wxLuaGetEventList_muhkuh_lua(m_eventCount);
    m_objectArray   = wxLuaGetObjectList_muhkuh_lua(m_objectCount);
    m_functionArray = wxLuaGetFunctionList_muhkuh_lua(m_functionCount);
    InitBinding();
}

void wxLuaBinding_muhkuh_lua::PreRegister(const wxLuaState& , bool , int )
{
}
void wxLuaBinding_muhkuh_lua::PostRegister(const wxLuaState& , bool , int )
{
}


// bind wxLuaBinding_muhkuh_lua to a single wxLuaState
bool wxLuaBinding_muhkuh_lua_bind(const wxLuaState& wxlState_)
{
    wxLuaState wxlState(wxlState_);
    wxCHECK_MSG(wxlState.Ok(), false, wxT("Invalid wxLuaState"));

    wxASSERT(!wxlState.GetLuaStateData()->m_bindings_registered);
    wxASSERT(!wxlState.GetLuaBinding(wxT("muhkuh_lua")));

    // ignore binding request when we already have muhkuh_lua registered
    if (wxlState.GetLuaBinding(wxT("muhkuh_lua")))
        return false;

    wxlState.GetLuaStateData()->m_bindingList.Append(new wxLuaBinding_muhkuh_lua());

    return true;
}
// initialize wxLuaBinding_muhkuh_lua for all wxLuaStates
bool wxLuaBinding_muhkuh_lua_init()
{
    static wxLuaBinding_muhkuh_lua m_binding;
    if (wxLuaBinding::GetBindingList()->Find(&m_binding)) return false;

    wxLuaBinding::GetBindingList()->Append(&m_binding);
    return true;
}


