// ---------------------------------------------------------------------------
// _luaif/muhkuh_lua.cpp was generated by genwxbind.lua 
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#include "wx/wxprec.h"

#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif


#include "wxlua/include/wxlstate.h"
#include "muhkuh_wxlua_bindings.h"


// ---------------------------------------------------------------------------
// Bind class muhkuh_plugin_instance
// ---------------------------------------------------------------------------

// Lua MetaTable Tag for Class 'muhkuh_plugin_instance'
int wxluatype_muhkuh_plugin_instance = WXLUA_TUNKNOWN;

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetHandle[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetHandle(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetHandle[1] = {{ wxLua_muhkuh_plugin_instance_GetHandle, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetHandle }};
// 	voidptr_long GetHandle()
static int LUACALL wxLua_muhkuh_plugin_instance_GetHandle(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call GetHandle
    long  returns = (long )self->GetHandle();
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetLuaCreateFn[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetLuaCreateFn(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetLuaCreateFn[1] = {{ wxLua_muhkuh_plugin_instance_GetLuaCreateFn, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetLuaCreateFn }};
// 	wxString GetLuaCreateFn()
static int LUACALL wxLua_muhkuh_plugin_instance_GetLuaCreateFn(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call GetLuaCreateFn
    wxString returns = (self->GetLuaCreateFn());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetName[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetName(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetName[1] = {{ wxLua_muhkuh_plugin_instance_GetName, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetName }};
// 	wxString GetName()
static int LUACALL wxLua_muhkuh_plugin_instance_GetName(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call GetName
    wxString returns = (self->GetName());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetTyp[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetTyp(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetTyp[1] = {{ wxLua_muhkuh_plugin_instance_GetTyp, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetTyp }};
// 	wxString GetTyp()
static int LUACALL wxLua_muhkuh_plugin_instance_GetTyp(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call GetTyp
    wxString returns = (self->GetTyp());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_IsUsed[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_IsUsed(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_IsUsed[1] = {{ wxLua_muhkuh_plugin_instance_IsUsed, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_IsUsed }};
// 	bool IsUsed()
static int LUACALL wxLua_muhkuh_plugin_instance_IsUsed(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call IsUsed
    bool returns = (self->IsUsed());
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_IsValid[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_IsValid(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_IsValid[1] = {{ wxLua_muhkuh_plugin_instance_IsValid, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_IsValid }};
// 	bool IsValid()
static int LUACALL wxLua_muhkuh_plugin_instance_IsValid(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call IsValid
    bool returns = (self->IsValid());
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}



// Map Lua Class Methods to C Binding Functions
wxLuaBindMethod muhkuh_plugin_instance_methods[] = {
    { "GetHandle", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetHandle, 1, NULL },
    { "GetLuaCreateFn", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetLuaCreateFn, 1, NULL },
    { "GetName", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetName, 1, NULL },
    { "GetTyp", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetTyp, 1, NULL },
    { "IsUsed", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_IsUsed, 1, NULL },
    { "IsValid", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_IsValid, 1, NULL },
    { 0, 0, 0, 0 },
};

int muhkuh_plugin_instance_methodCount = sizeof(muhkuh_plugin_instance_methods)/sizeof(wxLuaBindMethod) - 1;


