// ---------------------------------------------------------------------------
// This file was generated by genwxbind.lua 
//
// Any changes made to this file may be lost when file is regenerated.
// ---------------------------------------------------------------------------

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#include "wx/wxprec.h"


#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif

#include "wxlua/include/wxlstate.h"
#include "muhkuh_wxlua_bindings.h"


// ---------------------------------------------------------------------------
// Bind class muhkuh_binfile
// ---------------------------------------------------------------------------

// Lua MetaTable Tag for Class 'muhkuh_binfile'
int s_wxluatag_muhkuh_binfile = -1;

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_binfile_GetErrorMessage[] = { &s_wxluatag_muhkuh_binfile, NULL };
static int LUACALL wxLua_muhkuh_binfile_GetErrorMessage(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_binfile_GetErrorMessage[1] = {{ wxLua_muhkuh_binfile_GetErrorMessage, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_binfile_GetErrorMessage }};
// 	wxString GetErrorMessage()
static int LUACALL wxLua_muhkuh_binfile_GetErrorMessage(lua_State *L)
{
    wxLuaState wxlState(L);
    wxString returns;
    // get this
    muhkuh_binfile * self = (muhkuh_binfile *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_binfile);
    // call GetErrorMessage
    returns = (self->GetErrorMessage());
    // push the result string
    wxlState.lua_PushString(returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_binfile_GetFileName[] = { &s_wxluatag_muhkuh_binfile, NULL };
static int LUACALL wxLua_muhkuh_binfile_GetFileName(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_binfile_GetFileName[1] = {{ wxLua_muhkuh_binfile_GetFileName, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_binfile_GetFileName }};
// 	wxString GetFileName()
static int LUACALL wxLua_muhkuh_binfile_GetFileName(lua_State *L)
{
    wxLuaState wxlState(L);
    wxString returns;
    // get this
    muhkuh_binfile * self = (muhkuh_binfile *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_binfile);
    // call GetFileName
    returns = (self->GetFileName());
    // push the result string
    wxlState.lua_PushString(returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_binfile_GetSize[] = { &s_wxluatag_muhkuh_binfile, NULL };
static int LUACALL wxLua_muhkuh_binfile_GetSize(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_binfile_GetSize[1] = {{ wxLua_muhkuh_binfile_GetSize, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_binfile_GetSize }};
// 	int GetSize()
static int LUACALL wxLua_muhkuh_binfile_GetSize(lua_State *L)
{
    wxLuaState wxlState(L);
    int returns;
    // get this
    muhkuh_binfile * self = (muhkuh_binfile *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_binfile);
    // call GetSize
    returns = (self->GetSize());
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_binfile_GetText[] = { &s_wxluatag_muhkuh_binfile, NULL };
static int LUACALL wxLua_muhkuh_binfile_GetText(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_binfile_GetText[1] = {{ wxLua_muhkuh_binfile_GetText, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_binfile_GetText }};
// 	wxString GetText()
static int LUACALL wxLua_muhkuh_binfile_GetText(lua_State *L)
{
    wxLuaState wxlState(L);
    wxString returns;
    // get this
    muhkuh_binfile * self = (muhkuh_binfile *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_binfile);
    // call GetText
    returns = (self->GetText());
    // push the result string
    wxlState.lua_PushString(returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_binfile_IsOk[] = { &s_wxluatag_muhkuh_binfile, NULL };
static int LUACALL wxLua_muhkuh_binfile_IsOk(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_binfile_IsOk[1] = {{ wxLua_muhkuh_binfile_IsOk, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_binfile_IsOk }};
// 	bool IsOk()
static int LUACALL wxLua_muhkuh_binfile_IsOk(lua_State *L)
{
    wxLuaState wxlState(L);
    bool returns;
    // get this
    muhkuh_binfile * self = (muhkuh_binfile *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_binfile);
    // call IsOk
    returns = (self->IsOk());
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}



// Map Lua Class Methods to C Binding Functions
wxLuaBindMethod muhkuh_binfile_methods[] = {
    { "GetErrorMessage", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_binfile_GetErrorMessage, 1, NULL },
    { "GetFileName", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_binfile_GetFileName, 1, NULL },
    { "GetSize", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_binfile_GetSize, 1, NULL },
    { "GetText", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_binfile_GetText, 1, NULL },
    { "IsOk", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_binfile_IsOk, 1, NULL },
    { 0, 0, 0, 0 },
};

int muhkuh_binfile_methodCount = sizeof(muhkuh_binfile_methods)/sizeof(wxLuaBindMethod) - 1;


// ---------------------------------------------------------------------------
// Bind class muhkuh_plugin_instance
// ---------------------------------------------------------------------------

// Lua MetaTable Tag for Class 'muhkuh_plugin_instance'
int s_wxluatag_muhkuh_plugin_instance = -1;

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_plugin_instance_GetHandle[] = { &s_wxluatag_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetHandle(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetHandle[1] = {{ wxLua_muhkuh_plugin_instance_GetHandle, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_plugin_instance_GetHandle }};
// 	voidptr_long GetHandle()
static int LUACALL wxLua_muhkuh_plugin_instance_GetHandle(lua_State *L)
{
    wxLuaState wxlState(L);
    long returns;
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_plugin_instance);
    // call GetHandle
    returns = (long )self->GetHandle();
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_plugin_instance_GetLuaCreateFn[] = { &s_wxluatag_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetLuaCreateFn(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetLuaCreateFn[1] = {{ wxLua_muhkuh_plugin_instance_GetLuaCreateFn, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_plugin_instance_GetLuaCreateFn }};
// 	wxString GetLuaCreateFn()
static int LUACALL wxLua_muhkuh_plugin_instance_GetLuaCreateFn(lua_State *L)
{
    wxLuaState wxlState(L);
    wxString returns;
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_plugin_instance);
    // call GetLuaCreateFn
    returns = (self->GetLuaCreateFn());
    // push the result string
    wxlState.lua_PushString(returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_plugin_instance_GetName[] = { &s_wxluatag_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetName(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetName[1] = {{ wxLua_muhkuh_plugin_instance_GetName, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_plugin_instance_GetName }};
// 	wxString GetName()
static int LUACALL wxLua_muhkuh_plugin_instance_GetName(lua_State *L)
{
    wxLuaState wxlState(L);
    wxString returns;
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_plugin_instance);
    // call GetName
    returns = (self->GetName());
    // push the result string
    wxlState.lua_PushString(returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_plugin_instance_GetTyp[] = { &s_wxluatag_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetTyp(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetTyp[1] = {{ wxLua_muhkuh_plugin_instance_GetTyp, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_plugin_instance_GetTyp }};
// 	wxString GetTyp()
static int LUACALL wxLua_muhkuh_plugin_instance_GetTyp(lua_State *L)
{
    wxLuaState wxlState(L);
    wxString returns;
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_plugin_instance);
    // call GetTyp
    returns = (self->GetTyp());
    // push the result string
    wxlState.lua_PushString(returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_plugin_instance_IsUsed[] = { &s_wxluatag_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_IsUsed(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_IsUsed[1] = {{ wxLua_muhkuh_plugin_instance_IsUsed, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_plugin_instance_IsUsed }};
// 	bool IsUsed()
static int LUACALL wxLua_muhkuh_plugin_instance_IsUsed(lua_State *L)
{
    wxLuaState wxlState(L);
    bool returns;
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_plugin_instance);
    // call IsUsed
    returns = (self->IsUsed());
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}

static wxLuaArgTag s_wxluatagArray_wxLua_muhkuh_plugin_instance_IsValid[] = { &s_wxluatag_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_IsValid(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_IsValid[1] = {{ wxLua_muhkuh_plugin_instance_IsValid, WXLUAMETHOD_METHOD, 1, 1, s_wxluatagArray_wxLua_muhkuh_plugin_instance_IsValid }};
// 	bool IsValid()
static int LUACALL wxLua_muhkuh_plugin_instance_IsValid(lua_State *L)
{
    wxLuaState wxlState(L);
    bool returns;
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxlState.GetUserDataType(1, s_wxluatag_muhkuh_plugin_instance);
    // call IsValid
    returns = (self->IsValid());
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}



// Map Lua Class Methods to C Binding Functions
wxLuaBindMethod muhkuh_plugin_instance_methods[] = {
    { "GetHandle", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetHandle, 1, NULL },
    { "GetLuaCreateFn", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetLuaCreateFn, 1, NULL },
    { "GetName", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetName, 1, NULL },
    { "GetTyp", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetTyp, 1, NULL },
    { "IsUsed", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_IsUsed, 1, NULL },
    { "IsValid", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_IsValid, 1, NULL },
    { 0, 0, 0, 0 },
};

int muhkuh_plugin_instance_methodCount = sizeof(muhkuh_plugin_instance_methods)/sizeof(wxLuaBindMethod) - 1;


