// ---------------------------------------------------------------------------
// _luaif/serverkuh_lua.cpp was generated by genwxbind.lua 
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#include "wx/wxprec.h"

#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif


#include "wxlua/include/wxlstate.h"
#include "serverkuh_wxlua_bindings.h"


// ---------------------------------------------------------------------------
// Bind class muhkuh_plugin_instance
// ---------------------------------------------------------------------------

// Lua MetaTable Tag for Class 'muhkuh_plugin_instance'
int wxluatype_muhkuh_plugin_instance = WXLUA_TUNKNOWN;

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetHandle[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetHandle(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetHandle[1] = {{ wxLua_muhkuh_plugin_instance_GetHandle, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetHandle }};
// 	voidptr_long GetHandle()
static int LUACALL wxLua_muhkuh_plugin_instance_GetHandle(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call GetHandle
    long  returns = (long )self->GetHandle();
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetLuaCreateFn[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetLuaCreateFn(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetLuaCreateFn[1] = {{ wxLua_muhkuh_plugin_instance_GetLuaCreateFn, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetLuaCreateFn }};
// 	wxString GetLuaCreateFn()
static int LUACALL wxLua_muhkuh_plugin_instance_GetLuaCreateFn(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call GetLuaCreateFn
    wxString returns = (self->GetLuaCreateFn());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetName[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetName(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetName[1] = {{ wxLua_muhkuh_plugin_instance_GetName, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetName }};
// 	wxString GetName()
static int LUACALL wxLua_muhkuh_plugin_instance_GetName(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call GetName
    wxString returns = (self->GetName());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetTyp[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_GetTyp(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_GetTyp[1] = {{ wxLua_muhkuh_plugin_instance_GetTyp, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_GetTyp }};
// 	wxString GetTyp()
static int LUACALL wxLua_muhkuh_plugin_instance_GetTyp(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call GetTyp
    wxString returns = (self->GetTyp());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_IsUsed[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_IsUsed(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_IsUsed[1] = {{ wxLua_muhkuh_plugin_instance_IsUsed, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_IsUsed }};
// 	bool IsUsed()
static int LUACALL wxLua_muhkuh_plugin_instance_IsUsed(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call IsUsed
    bool returns = (self->IsUsed());
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_plugin_instance_IsValid[] = { &wxluatype_muhkuh_plugin_instance, NULL };
static int LUACALL wxLua_muhkuh_plugin_instance_IsValid(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_plugin_instance_IsValid[1] = {{ wxLua_muhkuh_plugin_instance_IsValid, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_plugin_instance_IsValid }};
// 	bool IsValid()
static int LUACALL wxLua_muhkuh_plugin_instance_IsValid(lua_State *L)
{
    // get this
    muhkuh_plugin_instance * self = (muhkuh_plugin_instance *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_plugin_instance);
    // call IsValid
    bool returns = (self->IsValid());
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}



// Map Lua Class Methods to C Binding Functions
wxLuaBindMethod muhkuh_plugin_instance_methods[] = {
    { "GetHandle", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetHandle, 1, NULL },
    { "GetLuaCreateFn", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetLuaCreateFn, 1, NULL },
    { "GetName", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetName, 1, NULL },
    { "GetTyp", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_GetTyp, 1, NULL },
    { "IsUsed", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_IsUsed, 1, NULL },
    { "IsValid", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_plugin_instance_IsValid, 1, NULL },
    { 0, 0, 0, 0 },
};

int muhkuh_plugin_instance_methodCount = sizeof(muhkuh_plugin_instance_methods)/sizeof(wxLuaBindMethod) - 1;


// ---------------------------------------------------------------------------
// Bind class muhkuh_wrap_xml
// ---------------------------------------------------------------------------

// Lua MetaTable Tag for Class 'muhkuh_wrap_xml'
int wxluatype_muhkuh_wrap_xml = WXLUA_TUNKNOWN;

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_wrap_xml_testDescription_getName[] = { &wxluatype_muhkuh_wrap_xml, NULL };
static int LUACALL wxLua_muhkuh_wrap_xml_testDescription_getName(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_wrap_xml_testDescription_getName[1] = {{ wxLua_muhkuh_wrap_xml_testDescription_getName, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_wrap_xml_testDescription_getName }};
// 	wxString testDescription_getName()
static int LUACALL wxLua_muhkuh_wrap_xml_testDescription_getName(lua_State *L)
{
    // get this
    muhkuh_wrap_xml * self = (muhkuh_wrap_xml *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_wrap_xml);
    // call testDescription_getName
    wxString returns = (self->testDescription_getName());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_wrap_xml_testDescription_getTestCnt[] = { &wxluatype_muhkuh_wrap_xml, NULL };
static int LUACALL wxLua_muhkuh_wrap_xml_testDescription_getTestCnt(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_wrap_xml_testDescription_getTestCnt[1] = {{ wxLua_muhkuh_wrap_xml_testDescription_getTestCnt, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_wrap_xml_testDescription_getTestCnt }};
// 	unsigned int testDescription_getTestCnt()
static int LUACALL wxLua_muhkuh_wrap_xml_testDescription_getTestCnt(lua_State *L)
{
    // get this
    muhkuh_wrap_xml * self = (muhkuh_wrap_xml *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_wrap_xml);
    // call testDescription_getTestCnt
    unsigned int returns = (self->testDescription_getTestCnt());
    // push the result number
    lua_pushnumber(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_wrap_xml_testDescription_getVersion[] = { &wxluatype_muhkuh_wrap_xml, NULL };
static int LUACALL wxLua_muhkuh_wrap_xml_testDescription_getVersion(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_wrap_xml_testDescription_getVersion[1] = {{ wxLua_muhkuh_wrap_xml_testDescription_getVersion, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_wrap_xml_testDescription_getVersion }};
// 	wxString testDescription_getVersion()
static int LUACALL wxLua_muhkuh_wrap_xml_testDescription_getVersion(lua_State *L)
{
    // get this
    muhkuh_wrap_xml * self = (muhkuh_wrap_xml *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_wrap_xml);
    // call testDescription_getVersion
    wxString returns = (self->testDescription_getVersion());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_wrap_xml_testDescription_setTest[] = { &wxluatype_muhkuh_wrap_xml, &wxluatype_TINTEGER, NULL };
static int LUACALL wxLua_muhkuh_wrap_xml_testDescription_setTest(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_wrap_xml_testDescription_setTest[1] = {{ wxLua_muhkuh_wrap_xml_testDescription_setTest, WXLUAMETHOD_METHOD, 2, 2, s_wxluatypeArray_wxLua_muhkuh_wrap_xml_testDescription_setTest }};
// 	bool testDescription_setTest(unsigned int uiTestIdx)
static int LUACALL wxLua_muhkuh_wrap_xml_testDescription_setTest(lua_State *L)
{
    // unsigned int uiTestIdx
    unsigned int uiTestIdx = (unsigned int)wxlua_getuintegertype(L, 2);
    // get this
    muhkuh_wrap_xml * self = (muhkuh_wrap_xml *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_wrap_xml);
    // call testDescription_setTest
    bool returns = (self->testDescription_setTest(uiTestIdx));
    // push the result flag
    lua_pushboolean(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_wrap_xml_test_getName[] = { &wxluatype_muhkuh_wrap_xml, NULL };
static int LUACALL wxLua_muhkuh_wrap_xml_test_getName(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_wrap_xml_test_getName[1] = {{ wxLua_muhkuh_wrap_xml_test_getName, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_wrap_xml_test_getName }};
// 	wxString test_getName()
static int LUACALL wxLua_muhkuh_wrap_xml_test_getName(lua_State *L)
{
    // get this
    muhkuh_wrap_xml * self = (muhkuh_wrap_xml *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_wrap_xml);
    // call test_getName
    wxString returns = (self->test_getName());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}

static wxLuaArgType s_wxluatypeArray_wxLua_muhkuh_wrap_xml_test_getVersion[] = { &wxluatype_muhkuh_wrap_xml, NULL };
static int LUACALL wxLua_muhkuh_wrap_xml_test_getVersion(lua_State *L);
static wxLuaBindCFunc s_wxluafunc_wxLua_muhkuh_wrap_xml_test_getVersion[1] = {{ wxLua_muhkuh_wrap_xml_test_getVersion, WXLUAMETHOD_METHOD, 1, 1, s_wxluatypeArray_wxLua_muhkuh_wrap_xml_test_getVersion }};
// 	wxString test_getVersion()
static int LUACALL wxLua_muhkuh_wrap_xml_test_getVersion(lua_State *L)
{
    // get this
    muhkuh_wrap_xml * self = (muhkuh_wrap_xml *)wxluaT_getuserdatatype(L, 1, wxluatype_muhkuh_wrap_xml);
    // call test_getVersion
    wxString returns = (self->test_getVersion());
    // push the result string
    wxlua_pushwxString(L, returns);

    return 1;
}



// Map Lua Class Methods to C Binding Functions
wxLuaBindMethod muhkuh_wrap_xml_methods[] = {
    { "testDescription_getName", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_wrap_xml_testDescription_getName, 1, NULL },
    { "testDescription_getTestCnt", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_wrap_xml_testDescription_getTestCnt, 1, NULL },
    { "testDescription_getVersion", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_wrap_xml_testDescription_getVersion, 1, NULL },
    { "testDescription_setTest", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_wrap_xml_testDescription_setTest, 1, NULL },
    { "test_getName", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_wrap_xml_test_getName, 1, NULL },
    { "test_getVersion", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_muhkuh_wrap_xml_test_getVersion, 1, NULL },
    { 0, 0, 0, 0 },
};

int muhkuh_wrap_xml_methodCount = sizeof(muhkuh_wrap_xml_methods)/sizeof(wxLuaBindMethod) - 1;


