# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------#
#   Copyright (C) 2011 by Christoph Thelen                                #
#   doc_bacardi@users.sourceforge.net                                     #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
#-------------------------------------------------------------------------#


#----------------------------------------------------------------------------
#
# Import the default compiler environments.
#
Import('atEnv')


#----------------------------------------------------------------------------
# This is the list of sources. The elements must be separated with whitespace
# (i.e. spaces, tabs, newlines). The amount of whitespace does not matter.
sources = """
	src/monitor.c
"""

astrCppPaths = ['src', 'platform/src/lib']
#----------------------------------------------------------------------------
#
# Build the netX500 files.
#
env_netx500 = atEnv.NETX500.Clone()
env_netx500.Append(CPPPATH = astrCppPaths)
src_netx500 = env_netx500.SetBuildPath('targets/netx500', 'src', sources)
libmi_netx500 = env_netx500.StaticLibrary('targets/libmi_netx500.a', src_netx500)


#----------------------------------------------------------------------------
#
# Build the netX56 files.
#
env_netx56 = atEnv.NETX56.Clone()
env_netx56.Append(CPPPATH = astrCppPaths)
src_netx56 = env_netx56.SetBuildPath('targets/netx56_monitor', 'src', sources)
libmi_netx56 = env_netx56.StaticLibrary('targets/libmi_netx56.a', src_netx56)


#----------------------------------------------------------------------------
#
# Build the netX50 files.
#
env_netx50 = atEnv.NETX50.Clone()
env_netx50.Append(CPPPATH = astrCppPaths)
src_netx50 = env_netx50.SetBuildPath('targets/netx50_monitor', 'src', sources)
libmi_netx50 = env_netx50.StaticLibrary('targets/libmi_netx50.a', src_netx50)


#----------------------------------------------------------------------------
#
# Build the netX10 files.
#
env_netx10 = atEnv.NETX10.Clone()
env_netx10.Append(CPPPATH = astrCppPaths)
src_netx10 = env_netx10.SetBuildPath('targets/netx10_monitor', 'src', sources)
libmi_netx10 = env_netx10.StaticLibrary('targets/libmi_netx10.a', src_netx10)


#----------------------------------------------------------------------------
#
# Export all libraries.
#
Export('libmi_netx500', 'libmi_netx56', 'libmi_netx50', 'libmi_netx10')
