# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------#
#   Copyright (C) 2011 by Christoph Thelen                                #
#   doc_bacardi@users.sourceforge.net                                     #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
#-------------------------------------------------------------------------#


#----------------------------------------------------------------------------
#
# Set up the Muhkuh Build System.
#
Import('atEnv')
import os.path

#----------------------------------------------------------------------------
# This is the list of sources. The elements must be separated with whitespace
# (i.e. spaces, tabs, newlines). The amount of whitespace does not matter.
sources = """
	src/start_mi_netx90.S
"""

strTargetPath = Dir('#targets/plugins/romloader/machine_interface/start_mi').get_path()

#----------------------------------------------------------------------------
#
# Build all files.
#

# The list of include folders. Here it is used for all files.
astrIncludePaths = ['src', '#targets/version']


# start_mi for netx 90 Rev.1 or Rev.2 communication CPU.
env_start_mi_netx90 = atEnv.NETX90.Clone()
env_start_mi_netx90.Append(CPPPATH = astrIncludePaths)
env_start_mi_netx90.Replace(LDFILE = 'src/netx90/netx90_com_intram.ld')
src_start_mi_netx90 = env_start_mi_netx90.SetBuildPath(os.path.join(strTargetPath, 'netx90'), 'src', sources)
elf_start_mi_netx90 = env_start_mi_netx90.Elf(os.path.join(strTargetPath, 'start_mi_netx90_com_intram.elf'), src_start_mi_netx90 )
bin_start_mi_netx90 = env_start_mi_netx90.ObjCopy(os.path.join(strTargetPath, 'start_mi_netx90_com_intram.bin'), elf_start_mi_netx90)
txt_start_mi_netx90 = env_start_mi_netx90.ObjDump(os.path.join(strTargetPath, 'start_mi_netx90_com_intram.txt'), elf_start_mi_netx90, OBJDUMP_FLAGS=['--disassemble', '--source', '--all-headers', '--wide'])
hboot_start_mi_netx90 = env_start_mi_netx90.HBootImage(os.path.join(strTargetPath, 'hboot_start_mi_netx90_com_intram.bin'), 'src/netx90/COM_to_INTRAM.xml', HBOOTIMAGE_KNOWN_FILES=dict({'tElfCOM': elf_start_mi_netx90}))

#----------------------------------------------------------------------------
#
# Export 

Export('hboot_start_mi_netx90')
