FROM ubuntu:16.04
MAINTAINER doc_bacardi@users.sourceforge.net
LABEL Description="This image contains the build environment for the MBS system on Ubuntu 16.04 ."

# Install the common packages.
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install --assume-yes curl gcc-multilib g++-multilib git lib32z1 make python2.7

# Add the repository for the build tools and install the key.
RUN echo 'deb http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_16.04/ /' > /etc/apt/sources.list.d/build_opensuse_org_home_docbacardi.list
RUN curl --location --silent http://download.opensuse.org/repositories/home:doc_bacardi/xUbuntu_16.04/Release.key | apt-key add -
RUN apt-get update

# Install the build tools from the new repository.
RUN apt-get install --assume-yes cmake3 mingw-w64-mbs

# Create a working folder.
RUN mkdir /tmp/work

# Copy the .mbs.xml file to the default user's home (which is /root).
COPY .mbs.xml /root/
