# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------#
#   Copyright (C) 2011 by Christoph Thelen                                #
#   doc_bacardi@users.sourceforge.net                                     #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
#-------------------------------------------------------------------------#


#----------------------------------------------------------------------------
#
# Set up the Muhkuh Build System.
#

SConscript('mbs/SConscript')
Import('env_default', 'env_netx500_default', 'env_netx50_default', 'env_netx10_default')

#----------------------------------------------------------------------------
# This is the list of sources. The elements must be separated with whitespace
# (i.e. spaces, tabs, newlines). The amount of whitespace does not matter.
sources_common = """
	src/header.S
	src/init_netx_test.S
	src/main.c
	src/options.c
	src/systime.c
	src/uartmon.c
"""


sources_custom_netx500 = """
	src/netx500/netx500_io_areas.c
"""


sources_custom_netx10 = """
	src/netx10/netx10_io_areas.c
"""

src_netx500 = Split(sources_common+sources_custom_netx500)
src_netx10  = Split(sources_common+sources_custom_netx10)


#----------------------------------------------------------------------------
#
# Build the netX500 files.
#
env_netx500_intram = env_netx500_default.Clone()
env_netx500_intram.Replace(LDFILE = 'src/netx500/netx500_intram.ld')
env_netx500_intram.Append(CPPPATH = ['src', 'src/netx500'])
src_netx500_intram = env_netx500_intram.SetBuildPath('targets/netx500_intram', 'src', src_netx500)
elf_netx500_intram = env_netx500_intram.Elf('targets/uartmon_netx500_intram', src_netx500_intram)
bin_netx500_intram = env_netx500_intram.ObjCopy('targets/uartmon_netx500_intram', elf_netx500_intram)
env_netx500_intram.DataArray('targets/uartmon_netx500_intram.c', bin_netx500_intram, DATAARRAY_NAME='auc_uartmon_netx500_intram')


#----------------------------------------------------------------------------
#
# Build the netX10 files.
#
env_netx10_intram = env_netx10_default.Clone()
env_netx10_intram.Replace(LDFILE = 'src/netx10/netx10_intram.ld')
env_netx10_intram.Append(CPPPATH = ['src', 'src/netx10'])
src_netx10_intram = env_netx10_intram.SetBuildPath('targets/netx10_intram', 'src', src_netx10)
env_netx10_intram.Replace(LDFILE = 'src/netx10/netx10_intram.ld')
elf_netx10_intram = env_netx10_intram.Elf('targets/uartmon_netx10_intram', src_netx10_intram)
bin_netx10_intram = env_netx10_intram.ObjCopy('targets/uartmon_netx10_intram', elf_netx10_intram)
env_netx10_intram.DataArray('targets/uartmon_netx10_intram.c', bin_netx10_intram, DATAARRAY_NAME='auc_uartmon_netx10_intram')

