# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------#
#   Copyright (C) 2011 by Christoph Thelen                                #
#   doc_bacardi@users.sourceforge.net                                     #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
#-------------------------------------------------------------------------#


#----------------------------------------------------------------------------
#
# Import the default compiler environments and the platform libraries.
#
Import('env_default', 'env_netx500_default',  'env_netx56_default', 'env_netx50_default', 'env_netx10_default')
Import('env_netx500_thumb_default', 'env_netx56_thumb_default', 'env_netx50_thumb_default', 'env_netx10_thumb_default')
Import('platform_lib_netx500', 'platform_lib_netx56', 'platform_lib_netx50', 'platform_lib_netx10')
Import('libmi_netx500', 'libmi_netx56', 'libmi_netx50', 'libmi_netx10')


#----------------------------------------------------------------------------
# This is the list of sources. The elements must be separated with whitespace
# (i.e. spaces, tabs, newlines). The amount of whitespace does not matter.
sources_monitor = """
	src/init_netx_test.S
	src/main.c
	src/uart.c
"""


sources_bootstrap = """
	src/bootstrap_init.S
	src/bootstrap.c
"""


sources_monitor_netx500 = """
	src/transport.c
"""

sources_monitor_netx56 = """
	src/netx56/netx56_usb_uart.c
	src/netx56/transport.c
"""

sources_monitor_netx50 = """
	src/netx50/transport.c
	src/netx50/usb.c
	src/netx50/usb_descriptors.c
	src/netx50/usb_globals.c
	src/netx50/usb_io.c
	src/netx50/usb_requests_top.c
"""

sources_monitor_netx10 = """
	src/transport.c
"""

#----------------------------------------------------------------------------
#
# Build the netX500 files.
#
env_netx500_monitor = env_netx500_default.Clone()
env_netx500_monitor.Append(CPPPATH = ['src', '../../machine_interface/netx/src', '#platform/src', '#platform/src/lib'])
env_netx500_monitor.Replace(LDFILE = File('src/netx500/netx500.ld'))
src_netx500_monitor = env_netx500_monitor.SetBuildPath('targets/netx500_monitor', 'src', sources_monitor + sources_monitor_netx500)
elf_netx500_monitor = env_netx500_monitor.Elf('targets/uartmon_netx500_monitor.elf', src_netx500_monitor + platform_lib_netx500 + libmi_netx500)
bin_netx500_monitor = env_netx500_monitor.ObjCopy('targets/uartmon_netx500_monitor.bin', elf_netx500_monitor)
arr_netx500_monitor = env_netx500_monitor.DataArray('targets/uartmon_netx500_monitor.c', bin_netx500_monitor, DATAARRAY_NAME='auc_uartmon_netx500_monitor')
sym_netx500_monitor = env_netx500_monitor.GccSymbolTemplate('targets/uartmon_netx500_monitor_run.h', elf_netx500_monitor, GCCSYMBOLTEMPLATE_TEMPLATE=File('templates/uartmon_netx500_monitor_run.h'))

env_netx500_bootstrap = env_netx500_thumb_default.Clone()
env_netx500_bootstrap.Replace(LDFILE = File('src/netx500/netx500_bootstrap.ld'))
env_netx500_bootstrap.Append(CPPPATH = ['src', '../../machine_interface/netx/src', '#platform/src', '#platform/src/lib', 'targets'])
src_netx500_bootstrap = env_netx500_bootstrap.SetBuildPath('targets/netx500_bootstrap', 'src', sources_bootstrap)
elf_netx500_bootstrap = env_netx500_bootstrap.Elf('targets/uartmon_netx500_bootstrap.elf', src_netx500_bootstrap)
bin_netx500_bootstrap = env_netx500_bootstrap.ObjCopy('targets/uartmon_netx500_bootstrap.bin', elf_netx500_bootstrap)
arr_netx500_bootstrap = env_netx500_bootstrap.DataArray('targets/uartmon_netx500_bootstrap.c', bin_netx500_bootstrap, DATAARRAY_NAME='auc_uartmon_netx500_bootstrap')
sym_netx500_bootstrap = env_netx500_bootstrap.GccSymbolTemplate('targets/uartmon_netx500_bootstrap_run.h', elf_netx500_bootstrap, GCCSYMBOLTEMPLATE_TEMPLATE=File('templates/uartmon_netx500_bootstrap_run.h'))

#----------------------------------------------------------------------------
#
# Build the netX56 files.
#
env_netx56_monitor = env_netx56_default.Clone()
env_netx56_monitor.Append(CPPPATH = ['src', '../../machine_interface/netx/src', '#platform/src', '#platform/src/lib'])
env_netx56_monitor.Replace(LDFILE = File('src/netx56/netx56.ld'))
src_netx56_monitor = env_netx56_monitor.SetBuildPath('targets/netx56_monitor', 'src', sources_monitor + sources_monitor_netx56)
elf_netx56_monitor = env_netx56_monitor.Elf('targets/uartmon_netx56_monitor.elf', src_netx56_monitor + platform_lib_netx56 + libmi_netx56)
bin_netx56_monitor = env_netx56_monitor.ObjCopy('targets/uartmon_netx56_monitor.bin', elf_netx56_monitor)
arr_netx56_monitor = env_netx56_monitor.DataArray('targets/uartmon_netx56_monitor.c', bin_netx56_monitor, DATAARRAY_NAME='auc_uartmon_netx56_monitor')
sym_netx56_monitor = env_netx56_monitor.GccSymbolTemplate('targets/uartmon_netx56_monitor_run.h', elf_netx56_monitor, GCCSYMBOLTEMPLATE_TEMPLATE=File('templates/uartmon_netx56_monitor_run.h'))

#----------------------------------------------------------------------------
#
# Build the netX50 files.
#
env_netx50_monitor = env_netx50_default.Clone()
env_netx50_monitor.Append(CPPPATH = ['src', '../../machine_interface/netx/src', '#platform/src', '#platform/src/lib'])
env_netx50_monitor.Replace(LDFILE = File('src/netx50/netx50.ld'))
src_netx50_monitor = env_netx50_monitor.SetBuildPath('targets/netx50_monitor', 'src', sources_monitor + sources_monitor_netx50)
elf_netx50_monitor = env_netx50_monitor.Elf('targets/uartmon_netx50_monitor.elf', src_netx50_monitor + platform_lib_netx50 + libmi_netx50)
bin_netx50_monitor = env_netx50_monitor.ObjCopy('targets/uartmon_netx50_monitor.bin', elf_netx50_monitor)
arr_netx50_monitor = env_netx50_monitor.DataArray('targets/uartmon_netx50_monitor.c', bin_netx50_monitor, DATAARRAY_NAME='auc_uartmon_netx50_monitor')
sym_netx50_monitor = env_netx50_monitor.GccSymbolTemplate('targets/uartmon_netx50_monitor_run.h', elf_netx50_monitor, GCCSYMBOLTEMPLATE_TEMPLATE=File('templates/uartmon_netx50_monitor_run.h'))

env_netx50_bootstrap = env_netx50_thumb_default.Clone()
env_netx50_bootstrap.Replace(LDFILE = File('src/netx50/netx50_bootstrap.ld'))
env_netx50_bootstrap.Append(CPPPATH = ['src', '../../machine_interface/netx/src', '#platform/src', '#platform/src/lib', 'targets'])
src_netx50_bootstrap = env_netx50_bootstrap.SetBuildPath('targets/netx50_bootstrap', 'src', sources_bootstrap)
elf_netx50_bootstrap = env_netx50_bootstrap.Elf('targets/uartmon_netx50_bootstrap.elf', src_netx50_bootstrap)
bin_netx50_bootstrap = env_netx50_bootstrap.ObjCopy('targets/uartmon_netx50_bootstrap.bin', elf_netx50_bootstrap)
arr_netx50_bootstrap = env_netx50_bootstrap.DataArray('targets/uartmon_netx50_bootstrap.c', bin_netx50_bootstrap, DATAARRAY_NAME='auc_uartmon_netx50_bootstrap')
sym_netx50_bootstrap = env_netx50_bootstrap.GccSymbolTemplate('targets/uartmon_netx50_bootstrap_run.h', elf_netx50_bootstrap, GCCSYMBOLTEMPLATE_TEMPLATE=File('templates/uartmon_netx50_bootstrap_run.h'))

#----------------------------------------------------------------------------
#
# Build the netX10 files.
#
env_netx10_monitor = env_netx10_default.Clone()
env_netx10_monitor.Append(CPPPATH = ['src', '../../machine_interface/netx/src', '#platform/src', '#platform/src/lib'])
env_netx10_monitor.Replace(LDFILE = File('src/netx10/netx10.ld'))
src_netx10_monitor = env_netx10_monitor.SetBuildPath('targets/netx10_monitor', 'src', sources_monitor + sources_monitor_netx10)
elf_netx10_monitor = env_netx10_monitor.Elf('targets/uartmon_netx10_monitor.elf', src_netx10_monitor + platform_lib_netx10 + libmi_netx10)
bin_netx10_monitor = env_netx10_monitor.ObjCopy('targets/uartmon_netx10_monitor.bin', elf_netx10_monitor)
arr_netx10_monitor = env_netx10_monitor.DataArray('targets/uartmon_netx10_monitor.c', bin_netx10_monitor, DATAARRAY_NAME='auc_uartmon_netx10_monitor')
sym_netx10_monitor = env_netx10_monitor.GccSymbolTemplate('targets/uartmon_netx10_monitor_run.h', elf_netx10_monitor, GCCSYMBOLTEMPLATE_TEMPLATE=File('templates/uartmon_netx10_monitor_run.h'))

env_netx10_bootstrap = env_netx10_thumb_default.Clone()
env_netx10_bootstrap.Replace(LDFILE = File('src/netx10/netx10_bootstrap.ld'))
env_netx10_bootstrap.Append(CPPPATH = ['src', '../../machine_interface/netx/src', '#platform/src', '#platform/src/lib', 'targets'])
src_netx10_bootstrap = env_netx10_bootstrap.SetBuildPath('targets/netx10_bootstrap', 'src', sources_bootstrap)
elf_netx10_bootstrap = env_netx10_bootstrap.Elf('targets/uartmon_netx10_bootstrap.elf', src_netx10_bootstrap)
bin_netx10_bootstrap = env_netx10_bootstrap.ObjCopy('targets/uartmon_netx10_bootstrap.bin', elf_netx10_bootstrap)
arr_netx10_bootstrap = env_netx10_bootstrap.DataArray('targets/uartmon_netx10_bootstrap.c', bin_netx10_bootstrap, DATAARRAY_NAME='auc_uartmon_netx10_bootstrap')
sym_netx10_bootstrap = env_netx10_bootstrap.GccSymbolTemplate('targets/uartmon_netx10_bootstrap_run.h', elf_netx10_bootstrap, GCCSYMBOLTEMPLATE_TEMPLATE=File('templates/uartmon_netx10_bootstrap_run.h'))

#----------------------------------------------------------------------------
#
# Build the diff and the zip distribution.
#
env_default.Diff('targets/uartmon_firmware.diff', arr_netx500_monitor + arr_netx56_monitor + arr_netx50_monitor + arr_netx10_monitor, DIFF_PATCHED_FOLDER='plugins/romloader/uart/netx')


tRelease = env_default.ArchiveList('zip')
tRelease.AddFiles('plugins/romloader/uart/netx/targets/',  arr_netx500_monitor,
                                                           sym_netx500_monitor,
                                                           arr_netx500_bootstrap,
                                                           sym_netx500_bootstrap)
tRelease.AddFiles('plugins/romloader/uart/netx/targets/',  arr_netx56_monitor,
                                                           sym_netx56_monitor)
tRelease.AddFiles('plugins/romloader/uart/netx/targets/',  arr_netx50_monitor,
                                                           sym_netx50_monitor,
                                                           arr_netx50_bootstrap,
                                                           sym_netx50_bootstrap)
tRelease.AddFiles('plugins/romloader/uart/netx/targets/',  arr_netx10_monitor,
                                                           sym_netx10_monitor,
                                                           arr_netx10_bootstrap,
                                                           sym_netx10_bootstrap)
tArc = env_default.Archive('targets/uartmon_firmware.zip', None, ARCHIVE_CONTENTS=tRelease)
