// ---------------------------------------------------------------------------
// This file was generated by genwxbind.lua 
//
// Any changes made to this file may be lost when file is regenerated.
// ---------------------------------------------------------------------------

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#include "wx/wxprec.h"


#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif

#include "wxlua/include/wxlstate.h"
#include "romloader_openocd_wxlua_bindings.h"


// ---------------------------------------------------------------------------
// wxLuaGetEventList_romloader_openocd_lua() is called to register events
// ---------------------------------------------------------------------------

wxLuaBindEvent* wxLuaGetEventList_romloader_openocd_lua(size_t &count)
{
    static wxLuaBindEvent eventList[] =
    {

        { 0, 0, 0 },
    };
    count = sizeof(eventList)/sizeof(wxLuaBindEvent) - 1;
    return eventList;
}

// ---------------------------------------------------------------------------
// wxLuaGetDefineList_romloader_openocd_lua() is called to register %define and %enum
// ---------------------------------------------------------------------------

wxLuaBindDefine* wxLuaGetDefineList_romloader_openocd_lua(size_t &count)
{
    static wxLuaBindDefine defineList[] =
    {

        { 0, 0 },
    };
    count = sizeof(defineList)/sizeof(wxLuaBindDefine) - 1;
    return defineList;
}

// ---------------------------------------------------------------------------

// wxLuaGetStringList_romloader_openocd_lua() is called to register %define %string
// ---------------------------------------------------------------------------

wxLuaBindString* wxLuaGetStringList_romloader_openocd_lua(size_t &count)
{
    static wxLuaBindString stringList[] =
    {

        { 0, 0 },
    };
    count = sizeof(stringList)/sizeof(wxLuaBindString) - 1;
    return stringList;
}

// ---------------------------------------------------------------------------
// wxLuaGetObjectList_romloader_openocd_lua() is called to register object and pointer bindings
// ---------------------------------------------------------------------------

wxLuaBindObject* wxLuaGetObjectList_romloader_openocd_lua(size_t &count)
{
    static wxLuaBindObject objectList[] =
    {

        { 0, 0, 0, 0 },
    };
    count = sizeof(objectList)/sizeof(wxLuaBindObject) - 1;
    return objectList;
}

// ---------------------------------------------------------------------------
// wxLuaGetFunctionList_romloader_openocd_lua() is called to register global functions
// ---------------------------------------------------------------------------

static wxLuaArgTag s_wxluatagArray_wxLua_function_romloader_openocd_create[] = { &s_wxluaarg_Number, NULL };
// %function %gc romloader *romloader_openocd_create(voidptr_long pvHandle)
static int LUACALL wxLua_function_romloader_openocd_create(lua_State *L)
{
    wxLuaState wxlState(L);
    romloader *returns;
    // voidptr_long pvHandle
    long pvHandle = (long)wxlua_getnumbertype(L, 1);
    // call romloader_openocd_create
    returns = (romloader *)romloader_openocd_create((void*)pvHandle);
    if (!wxlState.IsTrackedObject(returns)) wxlState.AddTrackedObject(returns);
    // push the result datatype
    wxlState.PushUserDataType(s_wxluatag_romloader, returns);

    return 1;
}
static wxLuaBindCFunc s_wxluafunc_wxLua_function_romloader_openocd_create[1] = {{ wxLua_function_romloader_openocd_create, WXLUAMETHOD_CFUNCTION, 1, 1, s_wxluatagArray_wxLua_function_romloader_openocd_create }};

// ---------------------------------------------------------------------------
// wxLuaGetFunctionList_romloader_openocd_lua() is called to register global functions
// ---------------------------------------------------------------------------

wxLuaBindMethod* wxLuaGetFunctionList_romloader_openocd_lua(size_t &count)
{
    static wxLuaBindMethod functionList[] =
    {
        { "romloader_openocd_create", WXLUAMETHOD_CFUNCTION, s_wxluafunc_wxLua_function_romloader_openocd_create, 1, NULL },

        { 0, 0, 0, 0 }, 
    };
    count = sizeof(functionList)/sizeof(wxLuaBindMethod) - 1;
    return functionList;
}



// ---------------------------------------------------------------------------
// wxLuaGetClassList_romloader_openocd_lua() is called to register classes
// ---------------------------------------------------------------------------

wxLuaBindClass* wxLuaGetClassList_romloader_openocd_lua(size_t &count)
{
    static wxLuaBindClass classList[] =
    {
        { "romloader", romloader_methods, romloader_methodCount, CLASSINFO(romloader), &s_wxluatag_romloader, NULL, NULL ,s_wxluadefineArray_None, 0, }, 

        { 0, 0, 0, 0, 0, 0, 0 }, 
    };
    count = sizeof(classList)/sizeof(wxLuaBindClass) - 1;

    return classList;
}


// ---------------------------------------------------------------------------
// wxLuaBinding_romloader_openocd_lua() - the binding class
// ---------------------------------------------------------------------------

// binding class
extern wxLuaBindClass  *wxLuaGetClassList_romloader_openocd_lua(size_t &count);
extern wxLuaBindDefine *wxLuaGetDefineList_romloader_openocd_lua(size_t &count);
extern wxLuaBindString *wxLuaGetStringList_romloader_openocd_lua(size_t &count);
extern wxLuaBindEvent  *wxLuaGetEventList_romloader_openocd_lua(size_t &count);
extern wxLuaBindObject *wxLuaGetObjectList_romloader_openocd_lua(size_t &count);
extern wxLuaBindMethod *wxLuaGetFunctionList_romloader_openocd_lua(size_t &count);


IMPLEMENT_DYNAMIC_CLASS(wxLuaBinding_romloader_openocd_lua, wxLuaBinding)

wxLuaBinding_romloader_openocd_lua::wxLuaBinding_romloader_openocd_lua() : wxLuaBinding()
{
    m_bindingName   = wxT("romloader_openocd_lua");
    m_nameSpace     = wxT("muhkuh");
    m_classArray    = wxLuaGetClassList_romloader_openocd_lua(m_classCount);
    m_defineArray   = wxLuaGetDefineList_romloader_openocd_lua(m_defineCount);
    m_stringArray   = wxLuaGetStringList_romloader_openocd_lua(m_stringCount);
    m_eventArray    = wxLuaGetEventList_romloader_openocd_lua(m_eventCount);
    m_objectArray   = wxLuaGetObjectList_romloader_openocd_lua(m_objectCount);
    m_functionArray = wxLuaGetFunctionList_romloader_openocd_lua(m_functionCount);
    InitBinding();
}

void wxLuaBinding_romloader_openocd_lua::PreRegister(const wxLuaState& , bool , int )
{
}
void wxLuaBinding_romloader_openocd_lua::PostRegister(const wxLuaState& , bool , int )
{
}


// bind wxLuaBinding_romloader_openocd_lua to a single wxLuaState
bool wxLuaBinding_romloader_openocd_lua_bind(const wxLuaState& wxlState_)
{
    wxLuaState wxlState(wxlState_);
    wxCHECK_MSG(wxlState.Ok(), false, wxT("Invalid wxLuaState"));

    wxASSERT(!wxlState.GetLuaStateData()->m_bindings_registered);
    wxASSERT(!wxlState.GetLuaBinding(wxT("romloader_openocd_lua")));

    // ignore binding request when we already have romloader_openocd_lua registered
    if (wxlState.GetLuaBinding(wxT("romloader_openocd_lua")))
        return false;

    wxlState.GetLuaStateData()->m_bindingList.Append(new wxLuaBinding_romloader_openocd_lua());

    return true;
}
// initialize wxLuaBinding_romloader_openocd_lua for all wxLuaStates
bool wxLuaBinding_romloader_openocd_lua_init()
{
    static wxLuaBinding_romloader_openocd_lua m_binding;
    if (wxLuaBinding::GetBindingList()->Find(&m_binding)) return false;

    wxLuaBinding::GetBindingList()->Append(&m_binding);
    return true;
}


