#define PACKAGE_VERSION "@MUHKUH_VERSION_ALL@"
#define PACKAGE_VERSION_VCS "@PROJECT_VERSION_VCS@"
#define PACKAGE_VERSION_VCS_LONG "@PROJECT_VERSION_VCS_LONG@"
#define PACKAGE_VCS_ORIGIN "@PROJECT_ORIGIN_VCS_URL@"
