#ifndef __VERSION_INFORMATION_H__
#define __VERSION_INFORMATION_H__


#define PROJECT_VERSION_VCS "@PROJECT_VERSION_VCS@"
#define PROJECT_VERSION_VCS_LONG "@PROJECT_VERSION_VCS_LONG@"
#define PROJECT_ORIGIN_VCS_URL "@PROJECT_ORIGIN_VCS_URL@"

#define MUHKUH_VERSION_ALL "@MUHKUH_VERSION_ALL@"


#endif  /* __VERSION_INFORMATION_H__ */
